== Validation

Since this profile is a profile of ABIS, all data wanting to conform to this profile must conform to ABIS. Demonstration of conformance to ABIS means passing ABIS validator validation.

Then, to show conformance to this profile and not just ABIS, data must also pass this Profile's validators.

=== ABIS Validation

ABIS requires data validation according to multiple validators:

* several background model validators
** e.g. the http://www.opengis.net/def/geosparql/validator/[https://li][GeoSPARQL Validator]
* https://w3id.org/tern/shapes/tern/[TERN Ontology Validator]
* https://linked.data.gov.au/def/brm[Biodiversity Record Model Validator]

These multiple validators are combined into a single ABIS Validator, for ease of use:

* https://linked.data.gov.au/def/abis/validator[ABIS Validator]

=== BDR Profile of ABIS Validation

This profile requires data validation according to multiple validators:

* ABIS Validator - as above
* Project Model Validator
* Data Release Model Validator
* Submission Manifest Validator

The ABIS, Project Model and Data Release Model validators are combined into a single validator for ease of use:

* https://linked.data.gov.au/def/bdr-pr/validator[BDR Profile of ABIS Validator]

[NOTE]
----
The Submission Manifest Model validator is not included in the BDR Profile of ABIS Validator since data according to the BDR Profile of ABIS and Submission Manifest Model can never be present in a single file and thus cannot be validated together. This is because BDR Profile of ABIS data is stored within data files which cannot include manifest information and manifest file content only indicates data files in submissions and does not contain ABIS data.
----

=== Multiple Validators

Just as the ABIS model is a collection of models and also inherits model elements from other models (see <<Multiple Models, Multiple Models>>), so too is the ABIS validator a collection of ABIS-created validators and inherited validation rules. For data to validly conform ABIS, it must also be valid according all these validators. Part use of ABIS may choose to be valid according to only some ABIS validators.

The following table lists all the validators relevant to ABIS and describes their roles.

[width="75%",cols="1,3,1,3"]
|===
| Validator | Description | Source | Notes

| https://ausbigg.github.io/abis/validators/abis.ttl[ABIS] | Validation rules implemented by ABIS only | ABIS | Imports many other validators
| https://ausbigg.github.io/abis/validators/bdr-profile.ttl[BDR Profile of ABIS] | For data intended for storage in the BDR | <<BDR Profile, BDR Profile>> | Imports the ABIS validator
| https://ausbigg.github.io/abis/validators/geo.ttl[GeoSPARQL] | For spatial data | <<GeoSPARQL, GeoSPARQL>> | Presented by the GeoSPARQL standard
| https://ausbigg.github.io/abis/validators/sosa.ttl[SOSA] | For sampling/observations data | <<SOSA, SOSA>> | Derived from the SOSA standard
| https://ausbigg.github.io/abis/validators/tern.ttl[TERN Ontology] | For TERN Ontology data | ABIS/BDR | The TERN Ontology validator, as presented by TERN
| https://ausbigg.github.io/abis/validators/abis-tern.ttl[ABIS Profile of TERN Ontology] | For data created according to the <<TERN Ontology, TERN Ontology>>, but for use in ABIS-based systems | <<TERN Ontology, TERN Ontology>> | Imports parts of the TERN validator but not all
| https://ausbigg.github.io/abis/validators/vocpub.ttl[VocPub] | For data vocabularies | <<VOCPUB, VocPub>> | Presented by VocPub
| https://ausbigg.github.io/abis/validators/bdrm.ttl[Biodiversity Records Model] | For data created according to the <<Biodiversity Record Model, Biodiversity Records Model>> | ABIS/BDR |
| https://ausbigg.github.io/abis/validators/bdr-profile.ttl[Project Model] | Validation rules implemented by the <<Projects Model, Projects Model>> only | ABIS |
| https://ausbigg.github.io/abis/validators/bdr-profile.ttl[Data Release Model] | Validation rules implemented by the <<Data Release Model, Data Release Model>> only | ABIS |
|===


=== Performing Validation

The preferred way to validate RDF data using the validators above is to use the https://portal.bdr.gov.au[ABIS Portal] which contains all the validators pre-loaded for use.

However, any one of a number of tools designed for <<SHACL, SHACL>> validation may be used and some may be more useful than the ABIS Portal for certain scenarios. Some such tools are:

* https://pypi.org/project/pyshacl/[pySHACL]
** free and open source Python SHACL validator
** can be used as a command line application or within Python scripting as a library
* https://shacl.org/playground/[SHACL Playground]
** online Javascript-based validator
** can be used in a browser
* http://tools.dev.kurrawong.ai/validator[KurrawongAI SHACL Validator]
** online pySHACL-based validator
** preloaded with the validators above and many others

