== Validation

Since this profile is a profile of ABIS, all data wanting to conform to this profile must conform to ABIS. Demonstration of conformance to ABIS means passing ABIS validator validation.

Then, to show conformance to this profile and not just ABIS, data must also pass this Profile's validators.

=== ABIS Validation

ABIS requires data validation according to multiple validators:

* several background model validators
** e.g. the http://www.opengis.net/def/geosparql/validator/[GeoSPARQL Validator]
* https://w3id.org/tern/shapes/tern/[TERN Ontology Validator]
* https://linked.data.gov.au/def/brm[Biodiversity Record Model Validator]

These multiple validators are combined into a single ABIS Validator, for ease of use:

* https://linked.data.gov.au/def/abis/validator[ABIS Validator]

=== BDR Profile of ABIS Validation

This profile requires data validation according to multiple validators:

* ABIS Validator
** as above
* Project Model Validator
** See <<annex-a, Annex A>>
* Data Release Model Validator
** See <<annex-b, Annex B>>
* Submission Manifest Validator
** See <<annex-c, Annex C>>

=== Combined Validators

The ABIS, Project Model and Data Release Model validators are combined into a single validator for ease of use:

* https://linked.data.gov.au/def/bdr-pr/validator[BDR Profile of ABIS Validator]

The Submission Manifest Model validator is not included in the BDR Profile of ABIS Validator. This is because BDR Profile of ABIS data is stored within data files which cannot include manifest information and Submission Manifest Model data is stored in files that indicate data files but that do not contain data themselves.

=== Performing Validation

All data submitted to the BDR for ingestion will be validated using all the validators listed above within the BDR's _Data Ingestion Pipeline_ software. In addition, all the validators listed above can be selected for individual or combined use on the https://bdr.gov.au[BDR Portal].

Since all the validators above are created using the open and standardised <<SHACL, SHACL>> validation language, data may be validated using them by any one of many open source and commercial tools and not just via the BDR Portal. Some such tools are:

* https://pypi.org/project/pyshacl/[pySHACL]
** free and open source Python SHACL validator
** can be used as a command line application or within Python scripting as a library
* https://shacl.org/playground/[SHACL Playground]
** free, online Javascript-based validator
** can be used in a browser
* http://tools.dev.kurrawong.ai/validator[KurrawongAI SHACL Validator]
** free, online pySHACL-based validator
** preloaded with the validators above and many others
* https://github.com/zazuko/rdf-validate-shacl[rdf-validate-shacl]
** free, open source Javascript SHACL validation code library
* https://graphdb.ontotext.com/documentation/10.8/shacl-validation.html[GraphDB's SHACL Validation capability]
** SHACL validation of data within GraphDB RDF database instances
** both commercial and free versions of GraphDB exist
* https://jena.apache.org/documentation/shacl/[Apache Jena's SHACL too]
** free, open source, Java RDF toolkit validation
** code library, command line, within database options

